ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'LICENSE'

source:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

build:
  - changed-files:
      - any-glob-to-any-file:
          - 'build.zig'
          - 'build.zig.zon'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file: 'build.zig.zon'
